[package]
name = "barbara"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = { version = "1.0.63" }
clap = { version = "3.2.19", features = ["derive"] }
serde_yaml = { version = "0.9.10" }
regex = { version = "1.5.4" }
colored = { version = "2.0.0" }